// This file is auto-generated by `npm --prefix video run capture:landing-previews`.
// Bump it whenever preview media is re-exported so browsers reload updated assets.
export const previewAssetVersion = '20260416T074904Z';
