import { spawn, execFileSync, type ChildProcess } from 'node:child_process';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { setTimeout as sleep } from 'node:timers/promises';

import { chromium } from 'playwright';

import { ScreencastRecorder } from './capture/screencastRecorder';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const VIDEO_ROOT = path.resolve(__dirname, '..');
const REPO_ROOT = path.resolve(VIDEO_ROOT, '..');
const FRONTEND_ROOT = path.join(REPO_ROOT, 'frontend');
const RAW_CAPTURE_DIR = path.join(VIDEO_ROOT, 'public', 'captures', 'landing-previews', 'raw');
const LANDING_PREVIEW_DIR = path.join(REPO_ROOT, 'landing', 'public', 'previews');
const PREVIEW_VERSION_FILE = path.join(
  REPO_ROOT,
  'landing',
  'src',
  'components',
  'previews',
  'generatedPreviewVersion.ts',
);

const FRONTEND_URL = 'http://127.0.0.1:5173';
const CAPTURE_VIEWPORT = { width: 1600, height: 1000 };
const PHASE_OUTPUT_SIZE = { width: 1150, height: 500 };
const PHASE_CROP = { x: 184, y: 34, width: 1320, height: 572 };
const PREROLL_MS = 300;
const POSTROLL_MS = 1800;

const cleanupFns: Array<() => void | Promise<void>> = [];
let signalHandled = false;
for (const sig of ['SIGINT', 'SIGTERM'] as const) {
  process.once(sig, () => {
    if (signalHandled) return;
    signalHandled = true;
    const forceExit = setTimeout(() => process.exit(130), 5_000);
    forceExit.unref();
    void (async () => {
      await Promise.allSettled(cleanupFns.map((fn) => Promise.resolve().then(fn)));
      clearTimeout(forceExit);
      process.exit(130);
    })();
  });
}

type PhasePreviewId =
  | 'ingest'
  | 'explore'
  | 'preprocess'
  | 'engineer'
  | 'train'
  | 'experiments'
  | 'deploy';

type HeroPresetId =
  | 'hero-upload'
  | 'hero-explore'
  | 'hero-preprocess'
  | 'hero-train'
  | 'hero-deploy';

type CapturePresetId = PhasePreviewId | HeroPresetId;

type LandingPreviewCapture = {
  status?: 'ready' | 'recording' | 'finished';
  start?: () => void;
};

const PHASE_PRESETS: readonly PhasePreviewId[] = [
  'ingest',
  'explore',
  'preprocess',
  'engineer',
  'train',
  'experiments',
  'deploy',
];

const HERO_PRESETS: readonly HeroPresetId[] = [
  'hero-upload',
  'hero-explore',
  'hero-preprocess',
  'hero-train',
  'hero-deploy',
];

const HERO_SEGMENTS: ReadonlyArray<{
  preset: HeroPresetId;
  start: number;
  end: number;
}> = [
  { preset: 'hero-upload', start: 0.3, end: 1.55 },
  { preset: 'hero-explore', start: 0.2, end: 1.25 },
  { preset: 'hero-preprocess', start: 0.2, end: 1.45 },
  { preset: 'hero-train', start: 0.2, end: 1.55 },
  { preset: 'hero-deploy', start: 0.2, end: 1.55 },
  { preset: 'hero-upload', start: 0.9, end: 1.55 },
];

async function waitForHttp(url: string, timeoutMs: number): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(1500) });
      if (res.ok || res.status === 404) {
        return true;
      }
    } catch {
      // Server is still starting.
    }
    await sleep(250);
  }
  return false;
}

async function ensureFrontendServer(): Promise<ChildProcess | null> {
  if (await waitForHttp(FRONTEND_URL, 1000)) {
    console.log(`[landing-previews] reusing frontend server at ${FRONTEND_URL}`);
    return null;
  }

  console.log('[landing-previews] starting frontend dev server...');
  const proc = spawn('npm', ['run', 'dev:ui', '--', '--host', '0.0.0.0', '--port', '5173'], {
    cwd: FRONTEND_ROOT,
    env: { ...process.env, FORCE_COLOR: '0' },
    stdio: 'inherit',
  });

  const up = await waitForHttp(FRONTEND_URL, 60_000);
  if (!up) {
    proc.kill('SIGTERM');
    throw new Error('Frontend dev server did not become ready within 60 seconds.');
  }

  return proc;
}

function ffmpeg(args: string[]) {
  execFileSync('ffmpeg', args, { stdio: 'pipe' });
}

function ffprobeSeconds(filePath: string): number {
  const output = execFileSync(
    'ffprobe',
    [
      '-v',
      'error',
      '-show_entries',
      'format=duration',
      '-of',
      'default=nw=1:nk=1',
      filePath,
    ],
    { encoding: 'utf-8', stdio: 'pipe' },
  );
  return Number.parseFloat(output.trim());
}

async function writePreviewVersionFile(version: string) {
  const contents = [
    '// This file is auto-generated by `npm --prefix video run capture:landing-previews`.',
    '// Bump it whenever preview media is re-exported so browsers reload updated assets.',
    `export const previewAssetVersion = '${version}';`,
    '',
  ].join('\n');

  await writeFile(PREVIEW_VERSION_FILE, contents, 'utf8');
}

async function capturePreset(preset: CapturePresetId): Promise<string> {
  const outputPath = path.join(RAW_CAPTURE_DIR, `${preset}.mp4`);
  await rm(outputPath, { force: true });

  const browser = await chromium.launch({ headless: true });
  let recorder: ScreencastRecorder | null = null;
  const cleanup = async () => {
    if (recorder) await recorder.stop().catch(() => {});
    await browser.close().catch(() => {});
  };
  cleanupFns.push(cleanup);
  try {
    const page = await browser.newPage({
      viewport: CAPTURE_VIEWPORT,
      deviceScaleFactor: 1,
    });

    await page.goto(`${FRONTEND_URL}/dev/landing-preview?preset=${preset}`, {
      waitUntil: 'domcontentloaded',
    });
    await page.waitForFunction(
      () =>
        (
          window as Window & { __landingPreviewCapture?: LandingPreviewCapture }
        ).__landingPreviewCapture?.status === 'ready',
    );
    await page.waitForTimeout(PREROLL_MS);

    recorder = await ScreencastRecorder.start({
      page,
      outputPath,
      size: CAPTURE_VIEWPORT,
      jpegQuality: 96,
    });

    await page.evaluate(() => {
      (
        window as Window & { __landingPreviewCapture?: LandingPreviewCapture }
      ).__landingPreviewCapture?.start?.();
    });
    await page.waitForFunction(
      () =>
        (
          window as Window & { __landingPreviewCapture?: LandingPreviewCapture }
        ).__landingPreviewCapture?.status === 'finished',
      {
        timeout: 15_000,
      },
    );
    await page.waitForTimeout(POSTROLL_MS);
    await recorder.stop();
    recorder = null;

    return outputPath;
  } finally {
    const idx = cleanupFns.indexOf(cleanup);
    if (idx >= 0) cleanupFns.splice(idx, 1);
    await cleanup();
  }
}

function exportLoopAssets(inputPath: string, id: PhasePreviewId) {
  const outputMp4 = path.join(LANDING_PREVIEW_DIR, `${id}.mp4`);
  const outputWebm = path.join(LANDING_PREVIEW_DIR, `${id}.webm`);
  const outputPoster = path.join(LANDING_PREVIEW_DIR, `${id}.webp`);
  const duration = ffprobeSeconds(inputPath);
  const fadeStart = Math.max(duration - 0.18, 0);
  const filter = [
    `crop=${PHASE_CROP.width}:${PHASE_CROP.height}:${PHASE_CROP.x}:${PHASE_CROP.y}`,
    `scale=${PHASE_OUTPUT_SIZE.width}:${PHASE_OUTPUT_SIZE.height}`,
    'fps=25',
    'format=yuv420p',
    'fade=t=in:st=0:d=0.18',
    `fade=t=out:st=${fadeStart.toFixed(3)}:d=0.18`,
  ].join(',');

  ffmpeg([
    '-y',
    '-i',
    inputPath,
    '-vf',
    filter,
    '-an',
    '-c:v',
    'libx264',
    '-preset',
    'slow',
    '-crf',
    '16',
    outputMp4,
  ]);

  ffmpeg([
    '-y',
    '-i',
    outputMp4,
    '-an',
    '-c:v',
    'libvpx-vp9',
    '-crf',
    '28',
    '-b:v',
    '0',
    '-deadline',
    'good',
    '-cpu-used',
    '2',
    outputWebm,
  ]);

  ffmpeg([
    '-y',
    '-ss',
    (duration / 2).toFixed(3),
    '-i',
    outputMp4,
    '-frames:v',
    '1',
    '-q:v',
    '82',
    outputPoster,
  ]);
}

function exportHeroMontage(heroInputs: Record<HeroPresetId, string>) {
  const heroMaster = path.join(RAW_CAPTURE_DIR, 'hero-montage-master.mp4');
  const outputMp4 = path.join(LANDING_PREVIEW_DIR, 'hero-montage.mp4');
  const outputWebm = path.join(LANDING_PREVIEW_DIR, 'hero-montage.webm');
  const outputPoster = path.join(LANDING_PREVIEW_DIR, 'hero-montage.webp');

  const ffmpegInputs = HERO_PRESETS.flatMap((preset) => ['-i', heroInputs[preset]]);
  const filterParts = HERO_SEGMENTS.map((segment, index) => {
    const inputIndex = HERO_PRESETS.indexOf(segment.preset);
    return `[${inputIndex}:v]trim=start=${segment.start}:end=${segment.end},setpts=PTS-STARTPTS[v${index}]`;
  });
  const concatInputs = HERO_SEGMENTS.map((_, index) => `[v${index}]`).join('');
  const filterComplex = `${filterParts.join(';')};${concatInputs}concat=n=${HERO_SEGMENTS.length}:v=1:a=0[vout]`;

  ffmpeg([
    '-y',
    ...ffmpegInputs,
    '-filter_complex',
    filterComplex,
    '-map',
    '[vout]',
    '-an',
    '-c:v',
    'libx264',
    '-preset',
    'slow',
    '-crf',
    '16',
    heroMaster,
  ]);

  ffmpeg([
    '-y',
    '-i',
    heroMaster,
    '-an',
    '-c:v',
    'libx264',
    '-preset',
    'slow',
    '-crf',
    '16',
    outputMp4,
  ]);

  ffmpeg([
    '-y',
    '-i',
    outputMp4,
    '-an',
    '-c:v',
    'libvpx-vp9',
    '-crf',
    '28',
    '-b:v',
    '0',
    '-deadline',
    'good',
    '-cpu-used',
    '2',
    outputWebm,
  ]);

  const duration = ffprobeSeconds(outputMp4);
  ffmpeg([
    '-y',
    '-ss',
    Math.min(duration / 2, 2.1).toFixed(3),
    '-i',
    outputMp4,
    '-frames:v',
    '1',
    '-q:v',
    '82',
    outputPoster,
  ]);
}

// Transcode a prerecorded, long-form hero walkthrough into the landing hero
// assets. Unlike `exportHeroMontage` (which stitches short Remotion captures
// at near-lossless CRF 16), this path tunes for ~7 minutes of real UI content:
// lower-quality CRF so file sizes stay under budget, threaded VP9 so the
// 2-pass encode finishes in minutes not hours, and a configurable poster
// offset since there's no montage midpoint to target.
//
// The source is a concatenation of UI recordings where the active content
// area shifts between clips (full app vs. centered modal vs. sparse
// workspace). A single uniform crop either leaves dark padding for the
// tight-modal clips or clips real content for the full-app clips. We instead
// apply per-scene crops via filter_complex: each segment is trimmed, cropped,
// scaled to a uniform 1280x800, fps-normalized, then concat'd back together.
//
// Scene boundaries and crop boxes were derived by dense-sampling the source
// at 1 Hz, measuring the content bounding box per sample with a PIL scan
// (r+g+b>40 threshold), classifying samples into wide / narrow / modal runs,
// and for each run picking the largest 16:10 rectangle that fits INSIDE the
// *inner* bbox (max-left, max-top, min-right, min-bot across samples, with a
// 5% robust percentile to ignore single-frame transition outliers). Because
// the crop edges sit inside content, the output has zero dark padding at the
// frame edges. Exception: the alembic-modal scene shows an isolated card on
// a pure-black backdrop — no inscribed crop preserves the whole modal, so we
// circumscribe it instead (a thin band of backdrop remains at the edges).
//
// All crops are 16:10 exact with even w/h (x264 yuv420p requires even dims),
// so the downstream scale=1280:800 is a pure linear resample.
type HeroSceneCrop = {
  start: number; // source seconds, inclusive
  end: number; // source seconds, exclusive
  x: number;
  y: number;
  w: number;
  h: number;
};

const HERO_SCENE_CROPS: ReadonlyArray<HeroSceneCrop> = [
  // Dashboard + "New Project" modal + "Create project" flow. Sidebar takes up
  // the leftmost ~140px, right side is dim dashboard content.
  { start: 0.0, end: 57.75, x: 146, y: 32, w: 1632, h: 1020 },
  // Explorer with CSV tabs + SQL editor pane. Full edge-to-edge app chrome.
  { start: 57.75, end: 112.75, x: 102, y: 4, w: 1712, h: 1070 },
  // "Select a dataset" modal over the processing workbook.
  { start: 112.75, end: 117.75, x: 116, y: 20, w: 1680, h: 1050 },
  // Processing / Feature Engineering / Training full-workflow — edge-to-edge.
  { start: 117.75, end: 309.75, x: 96, y: 4, w: 1712, h: 1070 },
  // Alembic package detail modal (circumscribed — keeps the full modal visible
  // at the cost of a small amount of black backdrop at the frame edges).
  { start: 309.75, end: 311.75, x: 414, y: 200, w: 1088, h: 680 },
  // Back to full-workflow — Training → Experiments list views.
  { start: 311.75, end: 429.75, x: 106, y: 10, w: 1696, h: 1060 },
  // Experiment detail with feature-importance chart + tail. Slightly narrower
  // content than the earlier wide scenes.
  { start: 429.75, end: 466.05, x: 120, y: 28, w: 1664, h: 1040 },
];

const HERO_OUTPUT_SIZE = { width: 1280, height: 800 } as const;
const HERO_OUTPUT_FPS = 30;

// Build a filter_complex string that:
//   1. trims [0:v] into one branch per scene
//   2. applies that scene's crop, scales to 1280x800, normalizes fps/SAR/pixfmt
//   3. concat=n=<N>:v=1:a=0 all branches into [vout]
// Scene end boundaries use trim=end=<t>; the final scene is left open-ended
// so we don't truncate if the source duration drifts by a frame or two.
function buildHeroFilterComplex(): string {
  const { width: OW, height: OH } = HERO_OUTPUT_SIZE;
  const parts: string[] = [];
  HERO_SCENE_CROPS.forEach((s, i) => {
    const isLast = i === HERO_SCENE_CROPS.length - 1;
    const trim = isLast
      ? `trim=start=${s.start.toFixed(3)}`
      : `trim=start=${s.start.toFixed(3)}:end=${s.end.toFixed(3)}`;
    parts.push(
      `[0:v]${trim},setpts=PTS-STARTPTS,` +
        `crop=${s.w}:${s.h}:${s.x}:${s.y},` +
        `scale=${OW}:${OH}:flags=lanczos,` +
        `fps=${HERO_OUTPUT_FPS},setsar=1,format=yuv420p` +
        `[v${i}]`,
    );
  });
  const concatInputs = HERO_SCENE_CROPS.map((_, i) => `[v${i}]`).join('');
  parts.push(
    `${concatInputs}concat=n=${HERO_SCENE_CROPS.length}:v=1:a=0[vout]`,
  );
  return parts.join(';');
}

// Pick the right scene for a given source timestamp so the poster uses the
// correct crop for its frame.
function heroSceneAt(tSeconds: number): HeroSceneCrop {
  for (const s of HERO_SCENE_CROPS) {
    if (tSeconds >= s.start && tSeconds < s.end) return s;
  }
  const fallback = HERO_SCENE_CROPS[HERO_SCENE_CROPS.length - 1];
  if (!fallback) throw new Error('HERO_SCENE_CROPS must not be empty');
  return fallback;
}

function transcodeHeroFromSource(srcPath: string) {
  const outputMp4 = path.join(LANDING_PREVIEW_DIR, 'hero-montage.mp4');
  const outputWebm = path.join(LANDING_PREVIEW_DIR, 'hero-montage.webm');
  const outputPoster = path.join(LANDING_PREVIEW_DIR, 'hero-montage.webp');

  const filterComplex = buildHeroFilterComplex();

  ffmpeg([
    '-y',
    '-i',
    srcPath,
    '-an',
    '-filter_complex',
    filterComplex,
    '-map',
    '[vout]',
    '-c:v',
    'libx264',
    '-profile:v',
    'main',
    '-level',
    '4.0',
    '-pix_fmt',
    'yuv420p',
    '-preset',
    'slow',
    '-crf',
    '28',
    '-g',
    '60',
    '-keyint_min',
    '60',
    '-movflags',
    '+faststart',
    outputMp4,
  ]);

  const passLog = path.join(os.tmpdir(), 'hero-vp9pass');
  const nullSink = process.platform === 'win32' ? 'NUL' : '/dev/null';
  const vp9Base = [
    '-y',
    '-i',
    srcPath,
    '-an',
    '-filter_complex',
    filterComplex,
    '-map',
    '[vout]',
    '-c:v',
    'libvpx-vp9',
    '-b:v',
    '0',
    // VP9 CRF is quality-equivalent to ~(crf - 10) on x264's scale, so CRF 38
    // here tracks the H.264 CRF 28 target above. CRF 35 produced a WebM
    // larger than the MP4 it's supposed to alternate with.
    '-crf',
    '38',
    '-deadline',
    'good',
    '-cpu-used',
    '2',
    '-row-mt',
    '1',
    '-tile-columns',
    '2',
    '-g',
    '60',
    '-passlogfile',
    passLog,
  ];
  ffmpeg([...vp9Base, '-pass', '1', '-f', 'null', nullSink]);
  ffmpeg([...vp9Base, '-pass', '2', outputWebm]);

  // Poster: default to 260s (deep into the full-workflow sections) unless the
  // caller specifies HERO_POSTER_OFFSET. Apply the crop box for whichever
  // scene contains that timestamp so the poster matches the video's framing.
  const posterOffset = Number.parseFloat(
    process.env.HERO_POSTER_OFFSET ?? '260',
  );
  const posterScene = heroSceneAt(posterOffset);
  ffmpeg([
    '-y',
    '-ss',
    posterOffset.toFixed(3),
    '-i',
    srcPath,
    '-frames:v',
    '1',
    '-vf',
    `crop=${posterScene.w}:${posterScene.h}:${posterScene.x}:${posterScene.y},` +
      `scale=${HERO_OUTPUT_SIZE.width}:${HERO_OUTPUT_SIZE.height}:flags=lanczos`,
    '-q:v',
    '82',
    outputPoster,
  ]);
}

async function main() {
  // Escape hatches:
  //   HERO_SOURCE_PATH=<path>  — skip Playwright capture of hero presets and
  //                              transcode this file as the hero instead.
  //   HERO_ONLY=1              — skip phase previews entirely; useful when
  //                              paired with HERO_SOURCE_PATH to re-emit just
  //                              the hero without disturbing phase assets.
  //   HERO_POSTER_OFFSET=<s>   — seconds offset for the hero WebP poster.
  const heroSourcePath = process.env.HERO_SOURCE_PATH;
  const heroOnly = process.env.HERO_ONLY === '1';
  const needsFrontend = !heroSourcePath || !heroOnly;

  await mkdir(RAW_CAPTURE_DIR, { recursive: true });
  await mkdir(LANDING_PREVIEW_DIR, { recursive: true });

  const frontendProc = needsFrontend ? await ensureFrontendServer() : null;
  const frontendCleanup = () => {
    if (frontendProc && !frontendProc.killed) {
      frontendProc.kill('SIGTERM');
    }
  };
  cleanupFns.push(frontendCleanup);
  try {
    const previewAssetVersion = new Date().toISOString().replace(/[-:.]/g, '');
    const heroInputs = {} as Record<HeroPresetId, string>;

    if (!heroSourcePath) {
      for (const preset of HERO_PRESETS) {
        console.log(`[landing-previews] capturing ${preset}...`);
        heroInputs[preset] = await capturePreset(preset);
      }
    }

    if (!heroOnly) {
      for (const preset of PHASE_PRESETS) {
        console.log(`[landing-previews] capturing ${preset}...`);
        const inputPath = await capturePreset(preset);
        console.log(`[landing-previews] exporting ${preset} assets...`);
        exportLoopAssets(inputPath, preset);
      }
    }

    if (heroSourcePath) {
      console.log(`[landing-previews] transcoding hero from ${heroSourcePath}...`);
      transcodeHeroFromSource(heroSourcePath);
    } else {
      console.log('[landing-previews] exporting hero montage...');
      exportHeroMontage(heroInputs);
    }
    await writePreviewVersionFile(previewAssetVersion);
    console.log(`[landing-previews] preview asset version: ${previewAssetVersion}`);
  } finally {
    const idx = cleanupFns.indexOf(frontendCleanup);
    if (idx >= 0) cleanupFns.splice(idx, 1);
    frontendCleanup();
  }
}

main().catch((error) => {
  if (signalHandled) return;
  console.error('[landing-previews] failed:', error);
  process.exit(1);
});
