/**
 * In-process cache for NL→SQL *generation*.
 *
 * `query_cache` (services/queryCache.ts) already caches the *result* of running
 * a given SQL string against a project. It does not help with the expensive
 * half: `runGeneratePipeline` makes two paid model calls — planning and SQL
 * generation — and it made them on every request, including for a question the
 * same user had just asked. The result cache could only engage *after* that
 * money had been spent, because the SQL it keys on does not exist until the
 * model has produced it.
 *
 * This cache sits between the two: the lookup happens once the schema context
 * is built (local, cheap) and before the first model call, so a hit skips both.
 *
 * ## The key is the whole correctness argument
 *
 * AutoML's workflow is upload → explore → preprocess → feature engineering.
 * Preprocessing changes columns and row counts, so the *same question against
 * the same project* legitimately needs different SQL after a preprocessing
 * step. Keying on `(projectId, question)` would serve stale SQL against a
 * schema that no longer exists.
 *
 * So the key covers every input that reaches the prompt: the question, the
 * table/column/dtype/rowcount context, the join candidates, the default table,
 * the model id, the reasoning effort, and a manually-maintained prompt
 * fingerprint. If it does not feed the prompt it is not in the key; if it feeds
 * the prompt it is.
 *
 * The context is hashed **in the order the pipeline received it**, not sorted.
 * Sorting would let two genuinely different prompts collide onto one key.
 *
 * ## Writes are confirmed, not optimistic
 *
 * Generated SQL can still fail to execute and get repaired
 * (`repairSqlFromExecutionErrorV2`). Storing at generation time would cache
 * known-broken SQL and re-pay for the repair on every future hit. Entries are
 * therefore only committed by the caller once the SQL has actually executed —
 * see `commitNlGeneration` and its use in routes/query/nlHandler.ts.
 */

import { createHash } from 'node:crypto';

import { appLogger } from '../../logging/logger.js';

import type {
  GeneratedSqlV2,
  JoinCandidate,
  SchemaTableContext
} from './types.js';

/**
 * Bump when the planning or SQL-generation prompt changes.
 *
 * The key cannot detect an edit to the prompt template itself, so a stale
 * fingerprint would serve SQL generated by the previous prompt. This is the one
 * part of the key that is not derived automatically, and the one that needs a
 * human to remember. It is cheap to bump and expensive to forget.
 */
const PROMPT_FINGERPRINT = 'nl2sql-v2.1';

function num(name: string, fallback: number): number {
  const raw = process.env[name];
  if (raw === undefined || raw.trim() === '') return fallback;
  const parsed = Number(raw);
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : fallback;
}

/**
 * Entries are small (a SQL string plus its explanation), so the ceiling is
 * about bounding a long-lived process rather than about memory pressure.
 */
const MAX_ENTRIES = num('AUTOML_NL2SQL_CACHE_MAX_ENTRIES', 500);
const TTL_MS = num('AUTOML_NL2SQL_CACHE_TTL_MS', 30 * 60 * 1000);

/** Escape hatch: set to "1" to disable without a redeploy of changed code. */
function cacheDisabled(): boolean {
  return process.env.AUTOML_NL2SQL_CACHE_DISABLED === '1';
}

export interface NlGenerationCacheInputs {
  projectId: string;
  /** The trimmed natural-language question, exactly as the prompt sees it. */
  query: string;
  defaultTableName?: string | null;
  tables: SchemaTableContext[];
  joinCandidates: JoinCandidate[];
  model: string;
  reasoningEffort?: string;
}

interface CacheEntry {
  payload: GeneratedSqlV2;
  expiresAt: number;
}

const cache = new Map<string, CacheEntry>();

/**
 * A stable fingerprint of everything the prompt is built from.
 *
 * Column dtypes and row counts are included because they are rendered into the
 * schema block the model reads — a preprocessing step that retypes a column
 * changes the prompt, and so must change the key.
 */
export function deriveNlGenerationCacheKey(inputs: NlGenerationCacheInputs): string {
  const canonical = JSON.stringify({
    v: PROMPT_FINGERPRINT,
    projectId: inputs.projectId,
    query: inputs.query,
    defaultTableName: inputs.defaultTableName ?? null,
    model: inputs.model,
    reasoningEffort: inputs.reasoningEffort ?? null,
    tables: inputs.tables.map((table) => ({
      tableName: table.tableName,
      sourceFilename: table.sourceFilename,
      rowCount: table.rowCount,
      columns: table.columns.map((column) => [column.name, column.dtype])
    })),
    joinCandidates: inputs.joinCandidates.map((candidate) => [
      candidate.leftTable,
      candidate.leftColumn,
      candidate.rightTable,
      candidate.rightColumn
    ])
  });

  return createHash('sha256').update(canonical).digest('hex');
}

/** A cached generation for this exact prompt, or undefined. */
export function readNlGeneration(key: string): GeneratedSqlV2 | undefined {
  if (cacheDisabled()) return undefined;

  const entry = cache.get(key);
  if (!entry) return undefined;

  if (entry.expiresAt <= Date.now()) {
    cache.delete(key);
    return undefined;
  }

  // Refresh recency for the LRU eviction below.
  cache.delete(key);
  cache.set(key, entry);
  return entry.payload;
}

/**
 * Commit a generation that has been shown to execute.
 *
 * Called by the request handler after the SQL ran, with the SQL that actually
 * ran — which is the repaired statement when a repair was needed.
 */
export function commitNlGeneration(key: string, payload: GeneratedSqlV2): void {
  if (cacheDisabled() || MAX_ENTRIES === 0 || TTL_MS === 0) return;

  cache.delete(key);
  cache.set(key, { payload, expiresAt: Date.now() + TTL_MS });

  // Oldest-first eviction; Map preserves insertion order and reads re-insert.
  while (cache.size > MAX_ENTRIES) {
    const oldest = cache.keys().next();
    if (oldest.done) break;
    cache.delete(oldest.value);
  }

  appLogger.debug('[nl2sqlCache] committed', { key, size: cache.size });
}

/** Test-only: drop every entry. */
export function __clearNlGenerationCacheForTests(): void {
  cache.clear();
}
